[wavefiles]
git-tree-sha1 = "debf9ce01961af51ed5406998778c860b91ce92b"
lazy = true

    [[wavefiles.download]]
    url = "https://rc.byu.edu/course/wavefiles.tar.gz"
    sha256 = "a771b944cdc836b46dfe97c232f1fcac89270cbbafb7ddf8b4476bad7fcabb92"