name = "WaveSim"
uuid = "784a90da-ac8c-451e-b1d9-9da584df6ccb"
authors = ["Michael Greenburg <michael_greenburg@byu.edu>"]
version = "0.1.0"

[deps]
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
